name: Check and Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.46.0, stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - name: Check and Run tests
        run: cargo test --features link-amalg --verbose

  build-macos:
    runs-on: macOS-latest
    strategy:
      matrix:
        rust: [1.47.0, stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - name: Check and Run tests
        run: cargo test --features link-amalg --verbose

  # build-windows:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       rust: [1.46.0, stable, beta, nightly]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: ${{ matrix.rust }}
  #       override: true
  #       profile: minimal
  #   - name: Install LLVM and Clang
  #     uses: KyleMayes/install-llvm-action@v1
  #     with:
  #       version: "12.0"
  #       directory: ${{ runner.temp }}/llvm
  #   - name: Check and Run tests
  #     run: cargo test --features link-amalg --verbose
